### ISSUE TITLE
Calculate hosts correctly

### ISSUE THREAD

**Issue by rtgibbons** [bwiggs/subnet-calculator#1]
https://github.com/bwiggs/subnet-calculator/blob/cdc529c1b0fd0222997bd19c240cb83ea32bc21a/main.js#L11

I think this should be 

`math.pow(2, 32 - this.networkbits) - 2 || 1`

**Comment by rtgibbons** [comment]
Or `this.hosts = (2 ** this.hostbits) - 2 || 1`

**Comment by rtgibbons** [comment]
What if

```
this.hosts = Math.max((2 ** this.hostbits) - Math.min(this.hostbits , 2), 1)
```

**Comment by bwiggs** [comment]
As you are aware, the world (including this company) is under distress due to SARS-COV-2. Due to time constraints, we won't be able to fix this report. PRs are welcome though!
